language: python
python: 3.6.1

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter



# run scripts
script:
  - nosetests test_book.py --with-coverage


after_success:
  - coveralls
  - codeclimate-test-reporter
