language: python
python: 3.6.1


# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install flask-jwt-extended



# run scripts
script:
  - coverage run -m unittest discover -s tests/
  - nosetests tests
  - coverage report



after_success:
  - coveralls
  - codeclimate-test-reporter
