language: python
python:
  - 2.7

# install dependencies
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls
  - pip install codeclimate-test-reporter



# run scripts
script:
  - nosetests tests


after_success:
  - coveralls
  - codeclimate-test-reporter
